### ISSUE TITLE
[v0.5.6] KeyError: 'dht22_sensor'

### ISSUE THREAD

**Issue by a-x-** [flyte/mqtt-io#162]
- [x] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Github Wiki](https://github.com/flyte/pi-mqtt-gpio/wiki) to see if the information there helps.

I also checked out 0.5.6 version of readme (it’s the same).

**Describe the bug**
I just copied:

```yaml
sensor_inputs:
  - name: dht22_temperature 
    module: dht22_sensor
    interval: 10
    digits: 4
    type: temperature # can be temperature or humidity
```

**Expected behavior**
Documentation matches the config/code.

**Error messages and traceback**
```

pi@rpi1:~ $ python3 -m pi_mqtt_gpio.server /home/pi/.config/pi-mqtt-gpio.yml
2021-02-11 00:19:56,218 mqtt_gpio (INFO): Startup
2021-02-11 00:20:00,838 mqtt_gpio (DEBUG): Last will set on 'wc/status' as 'dead'.
/home/pi/.local/lib/python3.7/site-packages/pi_mqtt_gpio/modules/raspberrypi.py:46: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  self.io.setup(pin, direction, pull_up_down=pullup, initial=initial)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/pi_mqtt_gpio/server.py", line 1281, in <module>
    main(args)
  File "/home/pi/.local/lib/python3.7/site-packages/pi_mqtt_gpio/server.py", line 1127, in main
    sens_conf
  File "/home/pi/.local/lib/python3.7/site-packages/pi_mqtt_gpio/server.py", line 691, in validate_sensor_input_config
    "pi_mqtt_gpio.modules.%s" % SENSOR_CONFIGS[sens_conf["module"]]["module"]
KeyError: 'dht22_sensor'
pi@rpi1:~ $

```

**Config**
```yaml

mqtt:
  host: 192.168.1.68
  port: 1883
  user: ""
  password: ""
  discovery: yes # HomeAssistant
  topic_prefix: wc

gpio_modules:
  - name: raspberrypi
    module: raspberrypi

sensor_modules:
  - name: wc_climate_dht22
    module: dht22
    type: DHT22 # can be  DHT11, DHT22 or AM2302
    pin: 23

sensor_inputs:
  - name: wc_temperature
    module: dht22_sensor
    interval: 10
    digits: 4
    type: temperature # can be temperature or humidity

  - name: wc_humidity
    module: dht22_sensor
    interval: 10
    digits: 4
    type: humidity
```

**Hardware**
 - Platform: Raspberry Pi
 - Connected hardware:  dht22

**System:**
 - OS: Raspbian
 - Python version: `python3 --version`: Python 3.7.3
 - User you're running as: pi
 - Using a virtualenv?: no

**Comment by a-x-** [comment]
dht22 w/o _sensor doesn’t work toooo

**Comment by a-x-** [comment]
Ok, I’m post COVID-19 stupid. 
I have to use my module name: `wc_climate_dht22`
