### ISSUE TITLE
MCP3008 Sensor Module Issue

### ISSUE THREAD

**Issue by skilletjohn** [flyte/mqtt-io#194]
MQTT IO is working fine with my digital inputs and outputs.  Sensor DS18B also working without issue.  I cannot get the MCP3008 module to work though.  I have confirmed that my MCP3008 ADC is working fine when tested with Adafruit MCP3008 python example code.  Any help would be appreciated.  Thank you in advance. 

Hardware:  Raspberry Pi 3B
OS: Debian Buster Lite
My config file and error log:
    #START - CONFIG.YML

```yaml
mqtt:
  host: 192.168.XXX.XXX
  port: 1883
  user: "mqttuser"
  password: "mqttpw"
  client_id: control_panel
  clean_session: true
  topic_prefix: cpanel
  status_payload_running: "online"
  status_payload_stopped: "offline"
  status_payload_dead: "offline"

gpio_modules:
  - name: raspberrypi
    module: raspberrypi

sensor_modules:
  - name: mcp_adc
    module: mcp3008
    
digital_outputs:
  - name: lt_garage
    module: raspberrypi
    pin: 5  #29 on board  
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
    
sensor_inputs:
  - name: test_adc
    module: mcp_adc
    channel: CH0
```

#END - CONFIG.YML

#START - TERMINAL

```
pi@control-panel:~ $ python3 -m mqtt_io config.yml
/home/pi/.local/lib/python3.7/site-packages/mqtt_io/modules/gpio/raspberrypi.py:56: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  self.io.setup(pin, direction, pull_up_down=pullup, initial=initial_int)
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/mqtt_io/__main__.py", line 85, in <module>
    main()
  File "/home/pi/.local/lib/python3.7/site-packages/mqtt_io/__main__.py", line 80, in main
    mqtt_gpio.run()
  File "/home/pi/.local/lib/python3.7/site-packages/mqtt_io/server.py", line 1136, in run
    self._init_sensor_modules()
  File "/home/pi/.local/lib/python3.7/site-packages/mqtt_io/server.py", line 244, in _init_sensor_modules
    self.sensor_modules[sens_config["name"]] = _init_module(sens_config, "sensor")
  File "/home/pi/.local/lib/python3.7/site-packages/mqtt_io/server.py", line 119, in _init_module
    return module_class(module_config)
  File "/home/pi/.local/lib/python3.7/site-packages/mqtt_io/modules/sensor/__init__.py", line 22, in __init__
    self.setup_module()
  File "/home/pi/.local/lib/python3.7/site-packages/mqtt_io/modules/sensor/mcp3008.py", line 46, in setup_module
    spi=SPI.SpiDev(self.config["spi_port"], self.config["spi_device"])
KeyError: 'spi_device'
```

#END - TERMINAL

**Comment by flyte** [comment]
Ah yes, I didn't add that config setting in by mistake. I've added it now, and a new version is building. It should be fixed on v2.1.3 once it's finished publishing.
