### ISSUE TITLE
pcf8574  KeyError: <PinPUD.OFF: 1>

### ISSUE THREAD

**Issue by IlmLV** [flyte/mqtt-io#216]
- [x] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Documentation](https://mqtt-io.app/) to see if the information there helps.

**Describe the bug**
Updated from v0.5.6 version to 2.2.6 and now I'm having error using pcf8574 module: `KeyError: <PinPUD.OFF: 1>`
After little digging found that there is new default pud state [PinPUD.OFF](https://github.com/flyte/mqtt-io/blob/d427b2295356ec7bcdfc6fef7ccbf18b3cbfc981/mqtt_io/modules/gpio/__init__.py#L197) previously default state was [None](https://github.com/flyte/mqtt-io/blob/86db2c6249a915274290227c34c8fe109701ccf1/pi_mqtt_gpio/server.py#L410).
In a result of that pcf8574 modules [pullup_map](https://github.com/flyte/mqtt-io/blob/d427b2295356ec7bcdfc6fef7ccbf18b3cbfc981/mqtt_io/modules/gpio/pcf8574.py#L25) lacks of this value map.
I believe changing it to `self.pullup_map = {PinPUD.OFF: None, PinPUD.UP: True, PinPUD.DOWN: False}` would fix the issue.

**Expected behavior**
Do not use pullup/pulldown if it is not necessary and run mqtt-io server without errors as it is supposed to be handled at this [line](https://github.com/flyte/mqtt-io/blob/d427b2295356ec7bcdfc6fef7ccbf18b3cbfc981/mqtt_io/modules/gpio/pcf8574.py#L38).

**Error messages and traceback**
```
mqtt-io    | Traceback (most recent call last):
mqtt-io    |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
mqtt-io    |     return _run_code(code, main_globals, None,
mqtt-io    |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
mqtt-io    |     exec(code, run_globals)
mqtt-io    |   File "/home/mqttio/.local/lib/python3.9/site-packages/mqtt_io/__main__.py", line 85, in <module>
mqtt-io    |     main()
mqtt-io    |   File "/home/mqttio/.local/lib/python3.9/site-packages/mqtt_io/__main__.py", line 80, in main
mqtt-io    |     mqtt_gpio.run()
mqtt-io    |   File "/home/mqttio/.local/lib/python3.9/site-packages/mqtt_io/server.py", line 1168, in run
mqtt-io    |     self._init_digital_inputs()
mqtt-io    |   File "/home/mqttio/.local/lib/python3.9/site-packages/mqtt_io/server.py", line 386, in _init_digital_inputs
mqtt-io    |     gpio_module.setup_pin_internal(PinDirection.INPUT, in_conf)
mqtt-io    |   File "/home/mqttio/.local/lib/python3.9/site-packages/mqtt_io/modules/gpio/__init__.py", line 207, in setup_pin_internal
mqtt-io    |     return self.setup_pin(
mqtt-io    |   File "/home/mqttio/.local/lib/python3.9/site-packages/mqtt_io/modules/gpio/pcf8574.py", line 39, in setup_pin
mqtt-io    |     self.io.port[pin] = self.pullup_map[pullup]
mqtt-io    | KeyError: <PinPUD.OFF: 1>
```

**Config**
```yaml
mqtt:
  [...]

gpio_modules:
  - name: pcf_1
    module: pcf8574
    i2c_bus_num: 1
    chip_addr: 0x22
    cleanup: False

digital_inputs:
  - name: master_bedroom_balcony_door
    module: pcf_1
    pin: 6
    on_payload: "OPEN"
    off_payload: "CLOSED"
    retain: yes
```

**Hardware**
 - Platform: Raspberry Pi 4
 - Connected hardware:  pcf8574

**System:**
 - OS: Raspbian using docker custom build [image](https://github.com/IlmLV/mqtt-io/blob/master/Dockerfile)
 - Python version: Python 3.9.4
 - User you're running as: pi
 - Using a virtualenv?: no

**Additional context**
-

**Comment by IlmLV** [comment]
also looks like using pcf8575 module would result in the same issue as [pullup_map](https://github.com/flyte/mqtt-io/blob/d427b2295356ec7bcdfc6fef7ccbf18b3cbfc981/mqtt_io/modules/gpio/pcf8575.py#L25) also has no mapping for PinPUD.OFF key
