### ISSUE TITLE
Docker Install Error

### ISSUE THREAD

**Issue by bsmith76s** [flyte/mqtt-io#275]
**Action description**
trying to setup a docker container on raspberry pi

**Previous attempts**
I have added user gpio group to pi user

**Error messages and traceback**
```
Traceback (most recent call last):
        File "/home/mqtt_io/mqtt_io/__main__.py", line 104, in main
            mqtt_gpio.run()
        File "/home/mqtt_io/mqtt_io/server.py", line 1227, in run
            self._init_digital_inputs()
        File "/home/mqtt_io/mqtt_io/server.py", line 387, in _init_digital_inputs
            gpio_module.setup_pin_internal(PinDirection.INPUT, in_conf)
        File "/home/mqtt_io/mqtt_io/modules/gpio/__init__.py", line 207, in setup_pin_internal
            return self.setup_pin(
        File "/home/mqtt_io/mqtt_io/modules/gpio/raspberrypi.py", line 56, in setup_pin
            self.io.setup(pin, direction, pull_up_down=pullup, initial=initial_int)
        RuntimeError: No access to /dev/mem.  Try running as root!
        Traceback (most recent call last):
        File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
            return _run_code(code, main_globals, None,
        File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
            exec(code, run_globals)
        File "/home/mqtt_io/mqtt_io/__main__.py", line 112, in <module>
            main()
        File "/home/mqtt_io/mqtt_io/__main__.py", line 104, in main
            mqtt_gpio.run()
        File "/home/mqtt_io/mqtt_io/server.py", line 1227, in run
            self._init_digital_inputs()
        File "/home/mqtt_io/mqtt_io/server.py", line 387, in _init_digital_inputs
            gpio_module.setup_pin_internal(PinDirection.INPUT, in_conf)
        File "/home/mqtt_io/mqtt_io/modules/gpio/__init__.py", line 207, in setup_pin_internal
            return self.setup_pin(
        File "/home/mqtt_io/mqtt_io/modules/gpio/raspberrypi.py", line 56, in setup_pin
            self.io.setup(pin, direction, pull_up_down=pullup, initial=initial_int)
        RuntimeError: No access to /dev/mem.
```

**Config**
```yaml
mqtt:
  host: XX.XX.XX.XX
  port: 1883
  user: "user"
  password: "password"
  topic_prefix: pimqtt/detach_garage
  status_topic: status
  status_payload_running: online
  status_payload_stopped: offline
  status_payload_dead: dead

gpio_modules:
  - name: raspberrypi
    module: raspberrypi

digital_outputs:
  - name: detach_door
    module: raspberrypi
    pin: 5
    on_payload: "ON"
    off_payload: "OFF"
#    inverted: true
#    initial: high
  - name: relay_2
    module: raspberrypi
    pin: 6 #GPIO
    on_payload: "ON"
    off_payload: "OFF"
#    inverted: true
#    initial: high
digital_inputs:
  - name: detach_door_closed
    module: raspberrypi
    pin: 22 # GPIO
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no
```

**Hardware**
 - Platform: Raspberry Pi
 - Connected hardware:  [GPIO module relay, sensors]

**System:**
 - OS: [Bullseye]
 - Python version: [21.1]
 - User you're running as: [tried both root, pi]

**Comment by bsmith76s** [comment]
I still have the issue with these branch. I did try ebekebe/mqtt-gpio fork and everything is up now. guess I will use it for now and continue testing with the branch.
