### ISSUE TITLE
pi-mqtt-gpio + VN + Pi2B

### ISSUE THREAD

**Issue by fleusner** [flyte/mqtt-io#46]
Hey Ellis, 

got an issue using your example code on a raspberry pi 2B.
Error log looks like this:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/server.py", line 473, in <module>
    gpio_config)
  File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/server.py", line 414, in configure_gpio_module
    return gpio_module.GPIO(gpio_config)
  File "/home/pi/ve/local/lib/python2.7/site-packages/pi_mqtt_gpio/modules/raspberrypi.py", line 16, in __init__
    import RPi.GPIO as gpio
ImportError: No module named RPi.GPIO
```

I've tried to use this one within the vn, but unfortunately it didn't work. :/

`pip install RPi.GPIO`

**Comment by flyte** [comment]
Hi @fleusner 

Sorry for such a delay.

Are you running the project with `sudo`? If so, it won't pick up your virtualenv. You'll need to use `sudo /home/pi/ve/bin/python` instead of `sudo python`.
