### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pointlevel** [flyte/mqtt-io#91]
Hello! 

Great project! I have followed the installation-instructions in the readme with virtualenv and supervisor, but the script wont start. 
I get this in the logfile: 

`2020-03-30 16:33:28,462 mqtt_gpio (INFO): Startup                                                                                                                     Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple                                                                                          Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (0.7.0)                                                                                   Traceback (most recent call last):                                                                                                                                      File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main                                                                                                    "__main__", fname, loader, pkg_name)                                                                                                                                File "/usr/lib/python2.7/runpy.py", line 72, in _run_code                                                                                                               exec code in run_globals                                                                                                                                            File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/server.py", line 887, in <module>                                                                            main(args)                                                                                                                                                          File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/server.py", line 759, in main                                                                                GPIO_MODULES[gpio_config["name"]] = configure_gpio_module(gpio_config)                                                                                              File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/server.py", line 437, in configure_gpio_module                                                               return gpio_module.GPIO(gpio_config)                                                                                                                                File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/modules/raspberrypi.py", line 19, in __init__                                                                import RPi.GPIO as gpio                                                                                                                                           ImportError: No module named RPi.GPIO `

Any idea?

**Comment by pointlevel** [comment]
Find the solution: 

`pip install RPi.GPIO`
