### ISSUE TITLE
startup with supervisroctl error

### ISSUE THREAD

**Issue by magrigian** [flyte/mqtt-io#99]
Hi, I'm sorry but I'm not able to get pi-mqtt-gpio running on boot. I'm running raspbian lite on pi2.
I followed several time your great instruction and I'm able to run using command line. Unfortunately I ended all my ideas on how to solve the proble.
With supervisorctl status become "running" but I get in the log: 

2020-04-30 00:35:57,351 mqtt_gpio (INFO): Startup
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (0.7.0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/server.py", line 887, in <module>
    main(args)
  File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/server.py", line 759, in main
    GPIO_MODULES[gpio_config["name"]] = configure_gpio_module(gpio_config)
  File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/server.py", line 437, in configure_gpi$
    return gpio_module.GPIO(gpio_config)
  File "/home/pi/ve/lib/python2.7/site-packages/pi_mqtt_gpio/modules/raspberrypi.py", line 19, in _$
    import RPi.GPIO as gpio
ImportError: No module named RPi.GPIO
2020-04-30 00:36:48,635 mqtt_gpio (INFO): Startup

Here is my pi-mqtt-gpio.conf
[program:pi_mqtt_gpio]
command = /home/pi/ve/bin/python -m pi_mqtt_gpio.server piGardenConfig.yml
directory = /home/pi
redirect_stderr = true
stdout_logfile = /var/log/pi-mqtt-gpio.log

and piGardenConfig.yml is in /home/pi

The complete procedure used to install
sudo apt-get update
sudo apt-get install supervisor
sudo apt-get install python-pip
sudo pip install --upgrade virtualenv
cd /home/pi
virtualenv ve
. ve/bin/activate
sudo pip install pi-mqtt-gpio
sudo nano /home/pi/piGardenConfig.yml
sudo nano /etc/supervisor/conf.d/pi-mqtt-gpio.conf
sudo supervisorctl update

Please suggest me a way to understand where I'm falling.  Thanks in advance

**Comment by magrigian** [comment]
FIND it!  I forgot to start at least one time the program before supervisroctl update. Sorry.
